### ISSUE TITLE
Infinite loading time if no font is specified

### ISSUE THREAD

**Issue by techneconn** [goldfire/phaser-webpack-loader#3]
`_loadFonts()` is never be resolved under following conditions
- font field does not exist in the manifest file
- font field is empty (like this -> `fonts: { }`)

However, since the `load()` function is waiting for both `_loadAssets()` and `_loadFonts()`,
it won't return...

I guess if fonts are not specified, `_loadFonts()` should be excluded
from `Promise.all` in the `_loadFonts()`.

**Comment by goldfire** [comment]
Thanks, I just pushed out a fix for this in v1.0.1.

**Comment by techneconn** [comment]
Thanks. It works great with/without webfonts now! 🎉
